### ISSUE TITLE
tillerino api key is causing the bot to break

### ISSUE THREAD

**Issue by TheRealZachTV** [pmrowla/gumiyabot#5]
With the new updates to the osu beatmap links the API does not work and causes the whole bot to break. (https://i.imgur.com/3zWj36o.png SC of the error it gives) If I remove the API key the bot works but I would like to have the PP show in chat again.

**Comment by pmrowla** [comment]
I'm a bit out of the loop on osu/tillerino API stuff these days but I'll look into this when I can, probably wont be able to get to it until next weekend at the earliest

**Comment by TheRealZachTV** [comment]
Any update on this? No rush just wondering :D

**Comment by pmrowla** [comment]
@TheRealZachTV sorry, I've been busy with IRL job stuff and haven't been able to get to this yet

**Comment by TheRealZachTV** [comment]
No problem! IRL stuff is more important then a osu request bot haha

**Comment by pmrowla** [comment]
This issue should be fixed in the latest release (0.1.4), just `install --upgrade` from pip
